### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by bgman111111** [DawfukFR/Oneplus_Android_Kernel_SM8250#1]
Thank I have 8250 I can't say him name because they will try . I make stock kernel work now I want update it to latest kernel. So can you help me. Your kernel work.

On latest TWRP it show picture, but touchscreen don't work and selinux is deny. I look and it is permissive but TWRP get deny command. Now do you know how to put from my stock kernel to your kernel. If you have mastodon, email or matrix account we can chat there I will give you kernel. Very good fbaly find working kernel r.

**Comment by DawfukFR** [comment]
Hey @bgman111111,

Actually the kernel work just the compilation of the dtbo didn't work for instant

If you need the dtbo you can contact me on telegram :
https://t.me/Dawfuk
